# 需要先安裝web station
# 需要先建立資料夾/volume1/docker/pihole/etc-dnsmasq.d
# 需要先建立資料夾/volume1/docker/pihole/etc-pihole

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole-bridge
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
    environment:
      - PIHOLE_UID=1111 #CHANGE_TO_YOUR_UID
      - PIHOLE_GID=65411 #CHANGE_TO_YOUR_GID
      - TZ=Asia/Taipei #CHANGE_TO_YOUR_TZ
      - WEBPASSWORD=YOURPASSWORD
      - DNSMASQ_LISTENING=local
      - WEB_PORT=8000
      - DNSMASQ_USER=pihole
      - FTLCONF_LOCAL_IPV4=192.168.xxx.xxx
    volumes:
      - /volume1/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /volume1/docker/pihole/etc-pihole:/etc/pihole
    ports:
      - 53:53/udp
      - 8000:8000/tcp
    restart: unless-stopped
